version: "3.8"

services:
  python-flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-flask
    container_name: python-flask-demo
    ports:
      - "8080:8080"
    volumes:
      - ./src:/home/app